[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4B8BFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1F2933"
font = "sans serif"
